import freemarker.core.ThreadInterruptionSupportTemplatePostProcessor;
public class FunctionUse3089 {
public void funcUse() {
ThreadInterruptionSupportTemplatePostProcessor threadinterruptionsupporttemplatepostprocessor = new ThreadInterruptionSupportTemplatePostProcessor();
threadinterruptionsupporttemplatepostprocessor.postProcess(null);
}
}