import freemarker.ext.jsp.CustomTagAndELFunctionCombiner.TemplateDirectiveModelAndSimpleMethodModel;
public class FunctionUse4630 {
public void funcUse() {
TemplateDirectiveModelAndSimpleMethodModel templatedirectivemodelandsimplemethodmodel = new TemplateDirectiveModelAndSimpleMethodModel();
templatedirectivemodelandsimplemethodmodel.explainTypeError(null);
}
}