import freemarker.ext.jsp.CustomTagAndELFunctionCombiner.TemplateTransformModelAndTemplateMethodModelEx;
public class FunctionUse4643 {
public void funcUse() {
TemplateTransformModelAndTemplateMethodModelEx templatetransformmodelandtemplatemethodmodelex = new TemplateTransformModelAndTemplateMethodModelEx();
templatetransformmodelandtemplatemethodmodelex.getWriter(null,null);
}
}