import freemarker.ext.jsp.CustomTagAndELFunctionCombiner.TemplateDirectiveModelAndTemplateMethodModelEx;
public class FunctionUse4635 {
public void funcUse() {
TemplateDirectiveModelAndTemplateMethodModelEx templatedirectivemodelandtemplatemethodmodelex = new TemplateDirectiveModelAndTemplateMethodModelEx();
templatedirectivemodelandtemplatemethodmodelex.exec(null);
}
}