import freemarker.ext.jsp.CustomTagAndELFunctionCombiner.TemplateTransformModelAndSimpleMethodModel;
public class FunctionUse4640 {
public void funcUse() {
TemplateTransformModelAndSimpleMethodModel templatetransformmodelandsimplemethodmodel = new TemplateTransformModelAndSimpleMethodModel();
templatetransformmodelandsimplemethodmodel.explainTypeError(null);
}
}